# we first compute the group and repos names (is there a more elegant way?)
space :=
space += 
GROUP = $(firstword $(subst /,$(space),$(subst $(MHDIR)/MathHub/,,$(shell pwd))))
REPOS = $(firstword $(subst /,$(space),$(subst $(MHDIR)/MathHub/$(GROUP),,$(shell pwd))))
STEXDIR = $(MHDIR)/ext/sTeX

include $(MHDIR)/make/Makefile.base.vars
include $(MHDIR)/make/Makefile.latex.vars
include $(MHDIR)/make/Makefile.latexml.vars
